{% set name = "django-schema-viewer" %}
{% set version = "0.5.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_schema_viewer-{{ version }}.tar.gz
  sha256: d5bdaa7cfec0827d1232f1d79f746ea5a7f42bf6abf2359615084acb230b2d1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.0

test:
  imports:
    - schema_viewer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pikhovkin/django-schema-viewer
  summary: Visualizes a DB schema based on Django models.
  dev_url: https://github.com/pikhovkin/django-schema-viewer
  doc_url: https://django-schema-viewer.up.railway.app/schema-viewer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
